<?php

namespace AppBundle\Repository\Football;

/**
 * LeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueRepository extends \Doctrine\ORM\EntityRepository
{
	public function collections()
	{
		$collections =  $this->createQueryBuilder('fl')
		->select('fl')
		->getQuery()
		->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
		if (count($collections) >= 1 ) {
			return $collections;
		}else{
			return null;
		}
	}
	public function getAssociatedTeams($leagueId){
		if(empty($leagueId)){
			return null;
		}
		$teams =  $this->createQueryBuilder('fl')
		->select('ft.name as name','ft.strip as strip')
		// ->from('AppBundle\Entity\Football\League', 'fl')
		->leftJoin(
			'AppBundle\Entity\Football\Team',
			'ft',
			\Doctrine\ORM\Query\Expr\Join::WITH,
			'ft.league_id = fl.id'
		)
		->where('ft.league_id = :id')
		->setParameter('id', $leagueId)
		->getQuery()
		->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
		if (count($teams) >= 1 ) {
			return $teams;
		}else{
			return null;
		}
	}
}
