<?php

namespace AppBundle\Repository\Football;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
	public function collections()
	{
		$collections =  $this->createQueryBuilder('ft')
		->select('ft.name','ft.strip')
		->getQuery()
		->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
		if (count($collections) >= 1 ) {
			return $collections;
		}else{
			return null;
		}
	}

	public function getAssociatedLeague($teamId){
		if(empty($teamId)){
			return null;
		}
		$teams =  $this->createQueryBuilder('ft')
		->select('fl.name as name')
		->leftJoin(
			'AppBundle\Entity\Football\League',
			'fl',
			\Doctrine\ORM\Query\Expr\Join::WITH,
			'fl.id = ft.league_id'
		)
		->where('ft.id = :id')
		->setParameter('id', $teamId)
		->getQuery()
		->setMaxResults(1)
		->getOneOrNullResult();
		if (!empty($teams)) {
			return isset($teams['name']) ? $teams['name'] : '';
		}else{
			return null;
		}
	}
}
